### ISSUE TITLE
No permission to open PR

### ISSUE THREAD

**Issue by mfodor** [KopiasCsaba/SDGStreamingJourney#1]
```
ERROR: Permission to KopiasCsaba/SDGStreamingJourney.git denied to mfodor.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I don't want to fork if I don't have to. :)

Can you set permissions to create/push to new branch?

**Comment by KopiasCsaba** [comment]
Hey Manuel! It's so great to hear from you!

I believe it would be the best to fork & PR me with a branch!
