### ISSUE TITLE
Feature: count down to an exact time

### ISSUE THREAD

**Issue by mfodor** [KopiasCsaba/SDGStreamingJourney#2]
Ability to count down to an exact time such as 14:30:00 for example.

This way it can be initiated any time and page refresh won't break either.

**Comment by KopiasCsaba** [comment]
I totally love the idea, I guess you have implemented it already (based on your previous issue), right?

Feel free to open a PR, or I'm happy to implement that too!

Nice to see you here, I hope you have found this useful:)

**Comment by mfodor** [comment]
Guessed right. See #3 .
